### ISSUE TITLE
Where to put nupkg?

### ISSUE THREAD

**Issue by godofgrunts** [ikkentim/LaGet#19]
I've installed LaGet on my server, but I cannot figure out where to place my nupkgs after I've created them so that they show up.

**Comment by ikkentim** [comment]
You need to push them to the server using nuget push https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#push 

make sure to use your own server nuget as the "Source" (see options)

**Comment by ikkentim** [comment]
use the php artisan user:create {name} {email} {password?} to create an API key, by the way.

**Comment by godofgrunts** [comment]
Oh. I had no idea. Thanks a lot.

**Comment by godofgrunts** [comment]
Everything worked! Thanks again.
